version: '3.3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
  envoy:
    build: ./envoy
    ports:
      - "10000:10000"
      - "8801:8801"
    depends_on: 
      - api
    environment:
      - SERVICE_DISCOVERY_PORT=8080
      - SERVICE_DISCOVERY_ADDRESS=host.docker.internal
      - LISTEN_PORT=10000