version: '3.3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
  envoy:
    build: ./envoy
    ports:
      - "80:80"
      - "8081:8081"
    environment: 
      - "ENVOY_UID=0"
    depends_on: 
      - api