name: Push to DockerHub

on: [push]

jobs:
   push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for articles service
        id: meta-articles-service
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: hmliversedge/refme-articles-api
      
      - name: Build and push articles Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta-articles-service.outputs.tags }}
          labels: ${{ steps.meta-articles-service.outputs.labels }}

      - name: Extract metadata (tags, labels) for envoy proxy
        id: meta-envoy-proxy
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: hmliversedge/refme-envoy-proxy

      - name: Build and push envoy proxy Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./envoy/staging
          push: true
          tags: ${{ steps.meta-envoy-proxy.outputs.tags }}
          labels: ${{ steps.meta-envoy-proxy.outputs.labels }}